defaults:
  - data: muse-ecg
  - model: contrastive
  - logger: wandb
  - callbacks: default
  - paths: default
  - trainer: gpu
  - hydra: default
  - override model/encoder: resnet4ecg
  - _self_

name: train
