_target_: continuity_contrastive_ecg.model.encoder.resnet4ecg.ResNet4ECG.initialize

ingest_mode: "mix"
ingest_ch_in: 1 # 2
ingest_kernel_size: 16
ingest_conv_stride: 1 # 5
ingest_pool_stride: 1 # 3
ingest_filt_ord: 1
ingest_ch_out: 64
ingest_layer_padding: same
ingest_sig_in: null
ingest_sig_out: null

resnet_ch_in: null
resnet_ch_out: 320
resnet_kernel_size: null
resnet_sig_in: null
resnet_conv_mode: null
resnet_layer_padding: null
resnet_layers: "1,1,1,1"
resnet_ch_list: 128,196,256,${model.rep_dims}
resnet_skip_stride: "2,5,5,5"
