_target_: continuity_contrastive_ecg.model.encoder.wav2vec4ecg.Wav2Vec4ECG.initialize

hidden_size: ${model.rep_dims}
num_hidden_layers: 8
intermediate_size: 2048
num_attention_heads: 8
feat_proj_dropout: 0.1
hidden_dropout: 0.1
layerdrop: 0.1
feat_extract_norm: group
conv_stride: [5, 2, 2]
conv_kernel: [10, 3, 3]
conv_dim: [512, 512, 512]
mask_time_prob: 0.0
mask_time_length: 10
mask_feature_prob: 0.0
mask_feature_length: 10
vocab_size: null
sampling_rate: ${data.sampling_rate}
padding_value: 0.0
do_normalize: false
return_attention_mask: false
